// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcqqmhggpzcnbwipgirc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcXFtaGdncHpjbmJ3aXBnaXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Nzg5MTksImV4cCI6MjA3MzA1NDkxOX0.gGVv0AkzJQJ3xEG7_FjX7Ri2hWMlo4lZfnUbF2wxbRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});